# Site settings
title: "ODAK"
tagline: "Open Data and Knowledge"

# URL - Deployment
#url: "connectingcontexts.org"
url: "https://universityofbrighton.github.io/odak"

# Handling Reading
safe: true
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
permalink: /:categories/:title/
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Contact
email: "csius@brighton.ac.uk"

# Social
#facebook: egsr-4668468684?
#twitter: egsr


# Use this for production
sass:
    style: compressed
exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]


theme: jekyll-theme-slate

collections:
  session:
    output: true
    permalink: /session/:path/
    title: Session
    sort_by: session_id